### ISSUE TITLE
bad static site rendering

### ISSUE THREAD

**Issue by fberrez** [puresyntax71/hugo-theme-chunky-poster#87]
I deployed my static site generated with `hugo` in a `nginx` container with the following configurations:

```yml
version: "3.7"

services:
  renard-resilient:
    image: nginx:latest
    container_name: renard-resilient
    labels:
      - traefik.backend=renard-resilient
      - traefik.frontend.rule=Host:renard-resilient.fr
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - proxy
    volumes:
      - .:/var/www/html # `.` is the content of the public folder
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  proxy:
    external: true
```

>Note: Please, do not take care about the traefik settings. It still does not work in local when I run my nginx container by exposing its port (80)

My `nginx.conf`:

```
events {}
http {
  server {
    listen 80;
    listen [::]:80;

    server_name renard-resilient.fr www.renard-resilient.fr;

    root /var/www/html/;
    index index.html;

    location / {
      try_files $uri $uri/ =404;
    }
  }
}

```

In my `config.toml`, I have `baseURL = "https://renard-resilient.fr"`.

---

My site renders like this:

![image](https://user-images.githubusercontent.com/25006376/78980283-e2596980-7b1d-11ea-8622-95206217205b.png)

I can access to the minified files with:

- [css](https://renard-resilient.fr/dist/main.37ab3f61b95417873748.min.css)
- [js](https://renard-resilient.fr/dist/main.d608eadfe5ac0688902e.min.js)

I do not understand why my static site does not render the css.

My static site has a good redering when I use `hugo server`.

Can you help me?
