### ISSUE TITLE
Aligning text to the center doesn't work

### ISSUE THREAD

**Issue by vladimirpetrovski** [puresyntax71/hugo-theme-chunky-poster#92]
I tried using `<div align="center">Lorem ipsum</di>`, but when using it like this, text disappears.

Is this an issue or is there a workaround this?

Thanks!

**Comment by puresyntax71** [comment]
Is this for a post? Perhaps check if you are using [`goldmark`](https://gohugo.io/getting-started/configuration-markup/#goldmark) for markup? I think you might need to add `unsafe` if that is the case:

```toml
[markup]
  [markup.goldmark.renderer]
    unsafe= true
```
